=== Akshay2598/vesuvius-fork/sahana-phase2/inc/lib_security/sec_policy.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.sahana.lk/security/policy"
xmlns="http://www.sahana.lk/security/policy"
elementFormDefault="qualified">

<xs:element name="sec_policy">
    <xs:complexType>
      <xs:sequence>
	<xs:element name="usercase" type="usercase" maxOccurs="unbounded" minOccurs="1" />
      </xs:sequence>
    </xs:complexType>
</xs:element>
<xs:complexType name="usercase">
  	<xs:sequence>
  		<xs:element name="funct" type="funct" maxOccurs="unbounded" minOccurs="1" />
  	</xs:sequence>
  	<xs:attribute name="name" type="xs:string"></xs:attribute>
</xs:complexType>
<xs:complexType name="funct">
  	<xs:sequence>
  		<xs:element name="tables">
  			<xs:complexType>
  				<xs:sequence>
  					<xs:element name="table" type="table" maxOccurs="unbounded" minOccurs="1"></xs:element>
  				</xs:sequence>
  			</xs:complexType>
  		</xs:element>
  	</xs:sequence>
  	<xs:attribute name="id" type="xs:string"></xs:attribute>
</xs:complexType>
 <xs:complexType name="table">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="perm" type="xs:string"></xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== Akshay2598/vesuvius-fork/sahana-phase2/mod/rms/sec_policy.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<sec_policy xmlns="http://www.sahana.lk/security/policy"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.sahana.lk/security/policy sec_policy.xsd">
	<usercase name="Requests">
		<funct id="shn_rms_req_new">
			<tables>	
					<table perm="r">camp_general</table>
					<table perm="r">config</table>
					<table perm="r">ct_catalogue</table>
					<table perm="r">field_options</table>
					<table perm="r">identity_to_person</table>
					<table perm="r">ims_inventory_records</table>
					<table perm="r">location</table>
					<table perm="r">location_details</table>
					<table perm="r">person_uuid</table>
					<table perm="r">rms_priority</table>
					<table perm="rc">rms_request</table>
					<table perm="rc">rms_req_item</table>
					<table perm="rc">ex_location</table>
			</tables>
		</funct>
		<funct id="shn_rms_req_ls">
			<tables>
					<table perm="r">contact</table>
					<table perm="r">location</table>
					<table perm="r">location_details</table>
					<table perm="r">person_uuid</table>
					<table perm="rc">rms_request</table>
			</tables>
		</funct>
		<funct id="shn_rms_req_sch">
			<tables>
					<table perm="r">rms_request</table>
					<table perm="r">person_uuid</table>
					<table perm="r">location_details</table>
					<table perm="r">contact</table>
			</tables>
		</funct>
	</usercase>
	<usercase name="Pledges">
		<funct id="shn_rms_plg_new">
			<tables>
					<table perm="ru">contact</table>
					<table perm="r">ct_catalogue</table>
					<table perm="r">ct_cat_unit</table>
					<table perm="r">ct_unit</table>
					<table perm="u">identity_to_person</table>
					<table perm="r">ims_inventory_records</table>
					<table perm="rc">person_uuid</table>
					<table perm="rc">rms_pledge</table>
					<table perm="r">rms_plg_item</table>
			</tables>
		</funct>
		<funct id="shn_rms_plg_ls">
			<tables>
					<table perm="r">contact</table>
					<table perm="r">person_uuid</table>
					<table perm="rc">rms_pledge</table>
			</tables>
		</funct>
		<funct id="shn_rms_plg_sch">
			<tables>
					<table perm="r">rms_pledge</table>
					<table perm="r">person_uuid</table>
					<table perm="r">contact</table>
					<table perm="r">rms_plg_item</table>
					<table perm="r">ct_catalogue</table>
					<table perm="r">ct_unit</table>
			</tables>
		</funct>
	</usercase>
	<usercase name="Manage">
		<funct id="shn_rms_mng_ff">
			<tables>
					<table perm="r">contact</table>
					<table perm="r">ct_catalogue</table>
					<table perm="r">location_details</table>
					<table perm="r">person_uuid</table>
					<table perm="rc">rms_fulfil</table>
					<table perm="r">rms_priority</table>
					<table perm="r">rms_req_item</table>
					<table perm="r">rms_request</table>
			</tables>
		</funct>
	</usercase>
</sec_policy>

=== Akshay2598/vesuvius-fork/sahana-phase2/mod/cs/sec_policy.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<sec_policy xmlns="http://www.sahana.lk/security/policy"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.sahana.lk/security/policy sec_policy.xsd">
	<usercase name="View Aid Catalog">
		<funct id="shn_cs_viewedit">
			<tables>
					<table perm="rud">ct_catalogue</table>
					<table perm="r">field_options</table>
					<table perm="d">ct_cat_unit</table>
					<table perm="rud">ct_unit</table>
					<table perm="rud">ct_unit_type</table>
			</tables>
		</funct>
	</usercase>
	<usercase name="Drill Down Catalog">
		<funct id="shn_cs_drill_down">
			<tables>
					<table perm="r">ct_catalogue</table>
			</tables>
		</funct>
	</usercase>
	<usercase name="Search Item Types">
		<funct id="shn_cs_search">
			<tables>
					<table perm="r">ct_catalogue</table>
					<table perm="r">ct_unit</table>
					<table perm="r">ct_unit_type</table>
			</tables>
		</funct>
	</usercase>
	<usercase name="Modify Catalog">
		<funct id="shn_cs_addmain">
			<tables>
					<table perm="rc">ct_catalogue</table>
			</tables>
		</funct>
		<funct id="shn_cs_addsub">
			<tables>
					<table perm="c">ct_catalogue</table>
			</tables>
		</funct>
		<funct id="shn_cs_additem">
			<tables>
					<table perm="rcd">ct_catalogue</table>
					<table perm="r">ct_unit_type</table>
					<table perm="cd">ct_cat_unit</table>
					<table perm="c">ct_suppliers</table>
			</tables>
		</funct>
	</usercase>
</sec_policy>

=== Akshay2598/vesuvius-fork/sahana-phase2/mod/admin/sec_policy.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<sec_policy xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="sec_policy.xsd">
	<usercase name="Default">
		<funct id="shn_admin_default">
			<tables>
				<table perm="r">incident</table>
				<table perm="r">location</table>
				<table perm="r">ct_catalogue</table>
				<table perm="r">config</table>
			</tables>
		</funct>
	</usercase>
	<usercase name="Disaster Incidents">
		<funct id="shn_admin_ims_config">
			<tables>
				<table perm="crd">config</table>
				<table perm="c">audit</table>
			</tables>
		</funct>
		<funct id="shn_admin_ims_level1">
			<tables>
				<table perm="r">config</table>
				<table perm="crud">incident</table>
			</tables>
		</funct>
		<funct id="shn_admin_ims_level2">
			<tables>
				<table perm="r">config</table>
				<table perm="crud">incident</table>
			</tables>
		</funct>
		<funct id="shn_admin_ims_level3">
			<tables>
				<table perm="r">config</table>
				<table perm="crud">incident</table>
			</tables>
		</funct>
	</usercase>
	<usercase name="Security Config">
		<funct id="shn_admin_acl_user_roles">
			<tables>
				<table perm="r">config</table>
			</tables>
		</funct>
		<funct id="shn_admin_add_user">
			<tables>
				<table perm="r">config</table>
				<table perm="cr">users</table>
				<table perm="cr">alt_logins</table>
				<table perm="c">person</table>
				<table perm="cu">person_uuid</table>
				<table perm="c">sys_user_to_group</table>
				<table perm="c">into password_event_log</table>
			</tables>
		</funct>
		<funct id="shn_admin_del_user">
			<tables>
				<table perm="r">config</table>
				<table perm="dr">users</table>
			</tables>
		</funct>
		<funct id="shn_admin_acl_user_edit_roles">
			<tables>
				<table perm="r">config</table>
				<table perm="r">person</table>
				<table perm="crd">sys_user_to_group</table>
				<table perm="r">sys_user_groups</table>
			</tables>
		</funct>
		<funct id="shn_admin_reset_pwd">
			<tables>
				<table perm="r">config</table>
				<table perm="r">person_uuid</table>
				<table perm="ur">users</table>
			</tables>
		</funct>
		<funct id="shn_admin_acl_change_user_status">
			<tables>
				<table perm="r">config</table>			
				<table perm="r">person_uuid</table>
				<table perm="ur">users</table>
			</tables>
		</funct>
		<funct id="shn_admin_acl_unlock_user">
			<tables>
				<table perm="r">config</table>			
				<table perm="r">person_uuid</table>
				<table perm="ur">users</table>
			</tables>
		</funct>
		<funct id="shn_admin_acl_privacy">
			<tables>
				<table perm="r">config</table>			
			</tables>
		</funct>
		<funct id="shn_admin_acl_data_classifications">
			<tables>
				<table perm="r">config</table>			
				<table perm="r">incident</table>
				<table perm="r">location</table>
				<table perm="r">ct_catalogue</table>
			</tables>
		</funct>
		<funct id="shn_admin_acl_data_privacy">
			<tables>
				<table perm="r">config</table>		
				<table perm="r">sys_data_classifications</table>
				<table perm="ru">sys_group_to_data_classification</table>
			</tables>
		</funct>
		<funct id="shn_admin_acl_data_classifications_tables">
			<tables>
				<table perm="r">config</table>	
				<table perm="r">sys_data_classifications</table>
				<table perm="ru">sys_tablefields_to_data_classification</table>		
			</tables>
		</funct>
		<funct id="shn_admin_acl_enable_acl">
			<tables>
				<table perm="ru">config</table>			
			</tables>
		</funct>
		<funct id="shn_admin_acl_enable_mods">
			<tables>
				<table perm="r">config</table>			
				<table perm="r">users</table>
				<table perm="cr">sys_group_to_module</table>
			</tables>
		</funct>
		<funct id="shn_admin_acl_enable_locking">
			<tables>
				<table perm="cr">config</table>			
				<table perm="r">users</table>
				<table perm="r">sys_group_to_module</table>
			</tables>
		</funct>
		<funct id="shn_admin_acl_event_log">
			<tables>
				<table perm="r">config</table>			
				<table perm="r">users</table>
				<table perm="r">sys_group_to_module</table>
				<table perm="r">password_event_log</table>
				<table perm="r">person_uuid</table>
				<table perm="r">field_options</table>
			</tables>
		</funct>
	</usercase>
	<usercase name="Config Values">
		<funct id="shn_admin_conf_list">
			<tables>
				<table perm="cr">config</table>			
				<table perm="r">person</table>
				<table perm="r">sys_user_to_group</table>
				<table perm="r">sys_user_groups</table>
				<table perm="r">sys_group_to_module</table>
				<table perm="r">users</table>
				<table perm="r">sys_tablefields_to_data_classification</table>
				<table perm="r">sys_group_to_data_classification"</table>
			</tables>
		</funct>
	</usercase>
</sec_policy>
